# Generated by Django 2.1.7 on 2019-03-08 12:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('installs', models.BigIntegerField(blank=True, null=True)),
                ('uninstalls', models.BigIntegerField(blank=True, null=True)),
                ('appid', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'apps',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=150, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Eventsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=150, null=True)),
                ('events', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('mtimestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('uptimestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('eventname', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.CharField(blank=True, max_length=200, null=True)),
                ('updatedate', models.DateField(blank=True, null=True)),
                ('created_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'eventsdata',
            },
        ),
        migrations.CreateModel(
            name='Fmpackagesdemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=150, null=True)),
                ('pkg', models.CharField(blank=True, max_length=200, null=True)),
                ('sid', models.CharField(blank=True, max_length=200, null=True)),
                ('f', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'fmpackagesdemo',
            },
        ),
        migrations.CreateModel(
            name='Fmpackageslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=150, null=True)),
                ('pkg', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'fmpackageslist',
            },
        ),
        migrations.CreateModel(
            name='Installdata',
            fields=[
                ('idinstalldata', models.AutoField(primary_key=True, serialize=False)),
                ('appid', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=1000, null=True)),
                ('deviceid', models.CharField(blank=True, max_length=1000, null=True)),
                ('sdkversion', models.CharField(blank=True, max_length=1000, null=True)),
                ('click_datetime', models.CharField(blank=True, max_length=1000, null=True)),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'installdata',
            },
        ),
        migrations.CreateModel(
            name='Mastertabledemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=200, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'mastertabledemo',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=150, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'users',
            },
        ),
    ]
